### ISSUE TITLE
Suggestion: Merge the Rods

### ISSUE THREAD

**Issue by Tysos24** [Friedhof5rb/SpaceBlockChess#10]
You could make it so that each color only has a single Rod of Control (or whatever name) that moves pieces on right-click, destroys them on left-click, and rotates them on shift-right-click.

This would polish the mod more and make things just that bit easier to work with.

**Comment by Friedhof5rb** [comment]
I have added the Universal Rod of Chess, which can move Pieces on right-click, destroy them on left-click and rotate them on shift-right-click. I have left the old Rods still in the Game as some People might still prefer to use them and also the Rod of Rotation allows rotating both ways depending on if you are sneaking or not, but here you go.
Have Fun!
