### ISSUE TITLE
Visual overhaul

### ISSUE THREAD

**Issue by Defetyre** [Friedhof5rb/SpaceBlockChess#6]
Make item frames invisible.
Make the chess pieces bigger.
Remove items' "background" unless it's a selected piece.
A new item model for the Rod of Moving that looks like a king's scepter of the respective color
All of this should drastically improve the visuals of the mod.

**Comment by Friedhof5rb** [comment]
First of all: I really appreciate the Feedback. Thank you very much for that.
I will look into your Ideas, but I am not quite sure how I would make the Chess Pieces bigger.
I will need to do some Research first. But yeah your Ideas sound absolutely doable with my current Knowledge.
So thank you :)

**Comment by Defetyre** [comment]
It's simple; just make their sprites bigger. This is needed for them to be clearly visible without the background.

**Comment by Friedhof5rb** [comment]
I have added all of your Requests. Changing the Size of the Sprites did not work, however I found another way to make the Figures bigger.
