### ISSUE TITLE
Z-fighting

### ISSUE THREAD

**Issue by Defetyre** [Friedhof5rb/SpaceBlockChess#9]
![image](https://github.com/Friedhof5rb/EschersGambit/assets/88449275/b5146cb3-2c8d-4b31-a3fc-fc96046db8ed)
There is visible stitching on move indicators near the edges of the board.
This can be fixed by making the move indicators a bit smaller than a normal block.

**Comment by Friedhof5rb** [comment]
Alright, will fix it, I think you can expect the fix with the next update.

**Comment by Friedhof5rb** [comment]
Fixed.
